---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Main webpage (posts)
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: Single pages
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: Section Pages
- type: directory
  path: _kids
  label: Kids
  create: all
  match: "**/*"
- type: directory
  path: _students
  label: Students
  create: all
  match: "**/*"
- type: directory
  path: _christmas
  label: Christmas
  create: all
  match: "**/*"
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --port 8080 --host 0.0.0.0 -d
    _site
